# Generated by Django 3.0.5 on 2020-04-14 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_encuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='preguntas',
        ),
        migrations.CreateModel(
            name='PlantillaEncuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntas', models.ManyToManyField(to='gestion.RespuestaUsuario')),
            ],
            options={
                'verbose_name': 'Plantilla de encuesta',
                'verbose_name_plural': 'Plantillas de encuestas',
            },
        ),
        migrations.AddField(
            model_name='encuesta',
            name='modeloEncuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.PlantillaEncuesta'),
        ),
    ]
