# Generated by Django 3.0.5 on 2020-04-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20200415_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fechaEncuesta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
