# Generated by Django 3.0.5 on 2020-04-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20200415_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestausuario',
            name='respuesta',
            field=models.BooleanField(default=False),
        ),
    ]
