# Generated by Django 3.0.5 on 2020-04-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descripción')),
                ('atencion', models.BooleanField(default=False, verbose_name='Requiere atención')),
            ],
            options={
                'verbose_name': 'Claseficador',
                'verbose_name_plural': 'Clasificadores',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=800)),
                ('descripcion', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descripción')),
                ('posicion', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaClasificador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.BooleanField(default=False)),
                ('clasificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.Clasificador')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='sintomas',
            field=models.ManyToManyField(blank=True, null=True, to='preguntas.Sintoma'),
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=500)),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.Recomendacion')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
            },
        ),
        migrations.AddField(
            model_name='clasificador',
            name='recomendaciones',
            field=models.ManyToManyField(to='preguntas.Recomendacion'),
        ),
    ]
