# Generated by Django 3.0.5 on 2020-04-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificador',
            name='recomendaciones',
            field=models.ManyToManyField(blank=True, null=True, to='preguntas.Recomendacion'),
        ),
    ]
