# Generated by Django 3.0.5 on 2020-04-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_auto_20200406_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntaclasificador',
            options={'verbose_name_plural': 'Clasificadores de Preguntas'},
        ),
    ]
