# Generated by Django 3.0.5 on 2020-04-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_auto_20200406_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificador',
            options={'verbose_name': 'Clasificador', 'verbose_name_plural': 'Clasificadores'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='preguntaclasificador',
            options={'verbose_name': 'Clasificador de Pregunta', 'verbose_name_plural': 'Clasificadores de Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='sintoma',
            options={'verbose_name': 'Síntoma', 'verbose_name_plural': 'Síntomas'},
        ),
        migrations.AlterField(
            model_name='clasificador',
            name='nombre',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='clasificador',
            name='recomendaciones',
            field=models.ManyToManyField(blank=True, to='preguntas.Recomendacion'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='sintomas',
            field=models.ManyToManyField(blank=True, to='preguntas.Sintoma'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='nombre',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='sintoma',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='preguntaclasificador',
            unique_together={('clasificador', 'pregunta', 'respuesta')},
        ),
    ]
